spring:
  application:
    name: test-stdio-mcp-server
  main:
    banner-mode: off
    web-application-type: none
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0
        stdio: true
logging:
  pattern:
    console:
